import {ADMIN_DASHBOARD_PAGE, ADMIN_DASHBOARD_USERS_PAGE, ADMIN_DASHBOARD_POSTS_PAGE} from "@/app/routes/adminDashboardPageRoutes";
import {HOME_PAGE, CHECKOUT_PAGE, ABOUT_PAGE, NEWS_PAGE, CONTACT_PAGE, PRODUCTS_PAGE, CATEGORIES_PAGE, PAYMENT_AND_DELIVERY_PAGE} from "@/app/routes/mainPageRoutes";
import {LOGIN_POPUP, CART_POPUP, REGISTER_POPUP} from "@/app/routes/popupRouter";

export {
    ADMIN_DASHBOARD_PAGE,
    HOME_PAGE,
    PRODUCTS_PAGE,
    PAYMENT_AND_DELIVERY_PAGE,
    CONTACT_PAGE,
    CHECKOUT_PAGE,
    NEWS_PAGE,
    ABOUT_PAGE,
    CATEGORIES_PAGE,
    LOGIN_POPUP,
    CART_POPUP,
    REGISTER_POPUP,
    ADMIN_DASHBOARD_USERS_PAGE,
    ADMIN_DASHBOARD_POSTS_PAGE
}
